### ISSUE TITLE
Implement containsAny, containsNone, containsAnyIterable, containsNoneIterable on RichIterable

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1006]
We have `contains`, `containsAll` and `containsAllIterable` today on `RichIterable`. The methods `containsAny(Collection)`, `containsNone(Collection)`, `containsAnyIterable`, and `containsNoneIterable` can be implemented as default methods by fusing `anySatisfy` and `nonSatisfy` with `contains`.

**Comment by hvydya** [comment]
Hi! I'd like to work on this issue. Can you assign this to me?

**Comment by donraab** [comment]
I've assigned the issue to you @hvydya. Thanks for volunteering!

**Comment by hvydya** [comment]
Greetings @donraab !
This is my first time contributing to open source. So, I've a few questions:
1. Are the versions above every method (`@since 10.3`) auto-generated? If not, what version should I mention?
2. Do I have to manually write the javadoc for all those four methods or are they generated in some other way?
3. Do I have to write any tests for the above methods? If yes, where and what type of tests?
4. `mvn clean install checkstyle:check findbugs:check --projects "!scala-unit-tests,!jmh-scala-tests,!jmh-tests" -DskipTests=true`. Running this command from `CONTRIBUTING.md` throws an error `bash: !scala-unit-tests,!jmh-scala-tests,!jmh-tests: event not found`. I wanted to check for violations. How do I fix this? My maven version is 3.6.0 and java version is 1.8.0_192. 
5. A sample of what I've to add in `RELEASE_NOTE_DRAFT.md` would help. As I didn't quite understand what to add in it.
6. For ECA checks, only my commit signoff email has to match with the email used to sign the ECA right? (My Github account has multiple emails registered but, I'll be signing the commits with the one I've used to sign the ECA).

**Comment by donraab** [comment]
Hi @hvydya!

Welcome to open source. I will do my best to answer your questions. I will defer to @nikhilnanivadekar for questions I don't know the answer to off hand.

1. No they are put in manually. The version you should use is 11.0 as that will be the next release.
2. Yes, you have to write the Javadoc for the methods.
3. Yes, you have to write tests for the methods. They are unit tests implemented with JUnit. You should add tests for each method in `AbstractRichIterableTestCase` where you will see two simple tests for `containsAll` and `containsAllIterable`. 
4. @nikhilnanivadekar can you offer advice here?
5. RELEASE_NOTE_DRAFT would include the text from your commit message. You can skip this step, and we will just focus on making sure your commit message is good so we can extract it later in the release notes.
6. Yes, your commit signoff email has to match the email you used for the ECA. @nikhilnanivadekar please confirm just to be double safe.

**Comment by Utkarshn10** [comment]
Hey @donraab @hvydya is any help required in this issue, since it's been 11 months and still this issue is not solved
