### ISSUE TITLE
Change Collectors2 class to return static instances for zero-argument methods which return Collectors

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections#1039]
It occurred to me that the following zero-argument methods on Collectors2 could return static instances of Collector, instead of creating new instances on every call, returning exactly the same instance.

- `toList`, `toImmutableList`, `toSortedList`, `toImmutableSortedList`
- `toSet`, `toImmutableSet`, `toSortedSet`, `toImmutableSortedSet`
- `toBag`, `toImmutableBag`, `toSortedBag`, `toImmutableSortedBag`
- `makeString` (with no parameters)
- `toStack`, `toImmutableStack`

**Comment by Desislav-Petrov** [comment]
Hi @donraab  - mind assigning to me please?

**Comment by Desislav-Petrov** [comment]
Hi @donraab, been looking into this and I'm thinking that making it return static instances will be tricky because of the generics. 

Just straight extract into constant won't work. I was thinking we can have some lookups of types that have already been created and just return the instances but this seems like over-engineering. Is there something I'm missing here or maybe you have some better ideas?

**Comment by mohrezaei** [comment]
@Desislav-Petrov Can't you just cast?

**Comment by Desislav-Petrov** [comment]
Thanks @mohrezaei - was thinking if we can somehow avoid casting but I don't think anything else can be done in this case - will go with that suggestion
