### ISSUE TITLE
Missing locking on SynchronizedMutableMap and SynchronizedBiMap for entries of entrySet

### ISSUE THREAD

**Issue by victornoel** [eclipse/eclipse-collections#1276]
I noticed the current implementation of those two classes `entrySet()` is as following:
```java
    @Override
    public Set<Entry<K, V>> entrySet()
    {
        synchronized (this.lock)
        {
            return SynchronizedMutableSet.of(this.getDelegate().entrySet(), this.lock);
        }
    }
```

It seems that the entries themselves being mutable, the lock should also apply to them.

**Comment by ayushdubey755** [comment]
hi @victornoel  can you please elaborate more

**Comment by victornoel** [comment]
@ayushdubey755 I mean that the lock should be exploited by each element of the entry set to synchronize the methods and in particular `Map.Entry#setValue()`, and not only to synchronize the set of entries.

**Comment by motlin** [comment]
Sorry, didn't mean to close this, but I don't think we necessarily ought to do this because java.util.Collections#synchronizedMap doesn't. The Javadoc warns It is imperative that the user manually synchronize on the returned map when traversing any of its collection views via [Iterator](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Iterator.html), [Spliterator](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Spliterator.html) or [Stream](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html). Reading the implementation, it's clear that Entry.setValue isn't synchronized.

On the one hand, it seems possible to implement this with some effort. On the other hand, if you're using Eclipse Collections, you're probably going to avoid ever creating Entry objects.

**Comment by victornoel** [comment]
@motlin right, this makes sense indeed. I think I created that issue when I was working with multi reader collection and noticed that protection against concurrent access was much more advanced in there than in this `SynchronizedMutableMap`, and thought that maybe it was overlooked.

I don't really have the need for this and as you say, if you are working with eclipse collections, maybe you just don't want to be manipulating mutable entry objects like this…

Feel free to close the issue then :)
