### ISSUE TITLE
Both api.factory.Lists and impl.factory.Lists are documented as "preferred way to create ..."

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse/eclipse-collections#1462]
I'm slightly confused by both the api and impl factories being documented as preferred way to create new collections.

Background: I was going to set up preferred imports to simplify code completion in Eclipse. Personally I tend to add only the impl variant to the favorites, because it contains the adapt() method needed to work with Java Collections and will therefore lead to a good code completion in all cases. For reference, this is the related preference page in Eclipse: 
![image](https://github.com/eclipse/eclipse-collections/assets/406876/3c443e6a-54e5-407f-a1b1-b9cb470eba70)

Now I'm wondering if there are any architectural or other concerns to recommend either the api or impl Lists/Sets/... classes in code completion. Any thoughts and insights from the maintainers?

**Comment by donraab** [comment]
I would recommend using the impl factory classes in most cases. The api version goes through JDK ServiceLoader to find the appropriate factory class. The impl version goes directly to the factory class. 

The api versions were created so that Eclipse Collections can create instances of containers in default methods in interfaces, thus allowing developers more flexibility at reducing duplicate code in Eclipse Collections. This is done this way so that we do not create direct dependencies between our api and impl jars. The downside is that we have duplicate classes to do that.
