### ISSUE TITLE
Idea project files in git repo?

### ISSUE THREAD

**Issue by jankotek** [eclipse/eclipse-collections#199]
I noticed git repo contains `.idea` folder and it is not excluded in `.gitignore`. 

First commit included dozen of `*.iml` files from subprojects. It was a bit annoying to filter them out. 

1) is there some good purpose to include project files in git repo? In general it is considered a bad practice, Idea usually imports maven projects just fine.

2) could we update `.gitignore` to exclude subproject files?

**Comment by PascalSchumacher** [comment]
The same goes for eclipse project files.

**Comment by motlin** [comment]
I want to keep the .idea/ folder checked in because it includes things like .idea/codeStyleSettings.xml which allow people to `Ctrl+Alt+L` reformat their code and pass the CheckStyle build with little to no effort. On the other hand, the *.iml files and the file .idea/misc.xml seem to have a lot of churn. I know that the *.iml files will be required if we set up builds in the [public TeamCity farm](https://blog.jetbrains.com/teamcity/2016/10/hosted-teamcity-for-open-source-a-new-home/). But until we do that, I could see removing the *.iml files if they're too annoying.

There's a relevant request in JetBrain's youtrack [here](https://youtrack.jetbrains.com/issue/IDEA-91607).

**Comment by jankotek** [comment]
I can live with `.idea` folder, but `*.iml` files are very annoying. Just opening EC in Idea creates 40 modifications to commit. I spend 70% of time dealing with those files:

![image](https://cloud.githubusercontent.com/assets/359021/24522772/4c688b32-1599-11e7-99dc-48ac1f2852e6.png)


Maven has task to generate Idea project files. Their creation could be automated on TeamCity.

Gitignore allows to whitelist files for inclusion with `!` prefix.

> There's a relevant request in JetBrain's youtrack here.
This issue is opened for a long time. 

Anyway, I am not sending pull request. I created my own .gitignore and it works for me.

**Comment by nikhilnanivadekar** [comment]
@PascalSchumacher would you like to contribute, to ignore the eclipse project files?
Thanks!

**Comment by motlin** [comment]
The same point goes for Eclipse. The files that share code style settings
and stuff should be kept. If there are files that are pure noise, we can
suppress them.
