### ISSUE TITLE
Optimize org.eclipse.collections.impl.set.sorted.immutable.ImmutableTreeSet#newSet to not create a new TreeSortedSet

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#216]
The below constructor creates a new SortedSet which is unnecessary as the delegating constructor calls a makes a toArray() call.

```
public static <T> ImmutableSortedSet<T> newSet(SortedSet<T> set)
{
    return new ImmutableTreeSet<>(TreeSortedSet.newSet(set));
}
```
```
private ImmutableTreeSet(SortedSet<T> sortedSet)
{
    this.delegate = (T[]) sortedSet.toArray();
    this.comparator = sortedSet.comparator();
}
```

**Comment by motlin** [comment]
I'm not sure these are redundant/unnecessary. If sortedSet.toArray() always returns a sorted array with no nulls in it *even if it's being mutated concurrently in another thread* then the copy is unnecessary. Maybe a better implementation would be to just call toArray() and then double check the invariants of the array since that would be O(n).
