### ISSUE TITLE
Provide p2 repository for Eclipse Collections

### ISSUE THREAD

**Issue by kthoms** [eclipse/eclipse-collections#223]
In order to be usable for Eclipse Plug-in development the Eclipse Collections framework has to provide a p2 repository. This repository should be deployed to a public consumable location.

**Comment by kthoms** [comment]
The issue could be solved either with a Maven Tycho based build or using [EBR](https://github.com/eclipse/ebr). PR #225 and #219 provide a proposal for both ways.

While first one is a rather frequently used approach to build plugins, features and p2 repositories, it disallows to include the build in the overall build process. This means a second build job has to be executed to do the Tycho based build. This could be the advantage of the EBR, where the p2 repo could be build within the same build job.

Result should be in both cases a zipped p2 repository, which has to be deployed to an accessible location, from where it could be used as part of a target platform definition. This would open Eclipse Collection for Eclipse plug-in development.

**Comment by nikhilnanivadekar** [comment]
@kthoms Thanks for the explanation!
Pinging @guw to check-in how far he has come with #219 .

In my opinion going with the recipe and having a single build makes sense. But will this additional build mandate using Eclipse during the build? We would like to keep the builds IDE agnostic.

**Comment by guw** [comment]
No, it should not require Eclipse. It will be IDE agnostic. I still haven't had time to finish the EBR stuff. It's been a pretty busy week and doesn't look to get better before April

**Comment by nikhilnanivadekar** [comment]
@guw appreciate the feedback. I think we are fine to wait, if the EBR setup will work. 
@kthoms , @guw here is a tentative road map of Eclipse Collections releases:
I am planning to call a code complete for 8.2.0 next week so that I can release it in time for The Great Indian Developer Summit.
We can pick up work for p2 repo in 8.3.0 and release it by end of May in time for the release train to pick it up.
We will start 9.0.0 where we will investigate and try and support Java 9 and release it by JavaOne.

This road map is yet to be vetted with other committers but timing-wise it makes sense.

Thanks a lot to both of you for helping us out with this!

**Comment by nikhilnanivadekar** [comment]
I would like to get an opinion from @kthoms , are you fine with this approach to use EBR?

**Comment by kthoms** [comment]
Yes, I'm fine with it. Thanks for asking.
