### ISSUE TITLE
Investigate and add support for Java 9

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#235]

**Comment by nikhilnanivadekar** [comment]
Step 1 and some discussion covered on #234

**Comment by Godin** [comment]
Citing http://openjdk.java.net/jeps/261 :
> The java.lang.reflect.AccessibleObject::setAccessible method cannot be used to gain access to members of packages that are not exported by their defining modules; an InaccessibleObjectException will be thrown.

As identified in https://github.com/eclipse/eclipse-collections/pull/234#issuecomment-289260035 affected classes are:
* `org.eclipse.collections.impl.utility.ArrayListIterate` because uses reflection to break into private fields of `java.util.ArrayList`
* `org.eclipse.collections.impl.collector.SerializableDoubleSummaryStatistics` because uses reflection to break into private fields of `java.util.DoubleSummaryStatistics`
* `org.eclipse.collections.impl.collector.SerializableLongSummaryStatistics` because uses reflection to break into private fields of `java.util.LongSummaryStatistics`
* `org.eclipse.collections.impl.collector.SerializableIntSummaryStatistics` because uses reflection to break into private fields of `java.util.IntSummaryStatistics`
* `org.eclipse.collections.impl.test.Verify` because uses reflection to break into private method `clone` of `java.lang.Object`

While possible and will be possible to workaround this using special JVM options ( http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-March/011763.html ), such options would have to be applied for any application that uses affected classes from eclipse-collections, which is inconvenient and defeats purpose of encapsulation of modules. Maybe if eclipse-collections will be itself modularized, then situation will be better as will be possible to grant access to `java-base` only for eclipse-collections module, but IMO this is anyway inconvenient for the users of a library. So IMO other solution should be applied.

Should be noted that `org.eclipse.collections.impl.map.mutable.ConcurrentHashMapUnsafe` is not affected even if it uses reflection to break into private member of `sun.misc.Unsafe`, because `Unsafe` remains accesible in Java 9. But in a long run (for Java 10) it should be updated to use Variable Handles (see http://openjdk.java.net/jeps/193) and some machinery for backward compatibility, either a usual runtime switch based on accessibility of Usafe, or maybe Multi-Release JAR Files (see http://openjdk.java.net/jeps/238).

For the `ArrayListIterate` you could catch `RuntimeException` instead of `SecurityException` as it is now (`InaccessibleObjectException` was introduced in Java 9 and is not subclass of `SecurityException` - http://download.java.net/java/jdk9/docs/api/java/lang/reflect/InaccessibleObjectException.html). This probably defeats some aspects of `ArrayListIterate`, but at least with degraded performance it will work under Java 9 (can't tell exact impact on performance as I never benchmarked eclipse-collections).

`Serializable*SummaryStatistics` similarly could degrade into non-serializable variants, but to me seems that this completely defeats their purpose. BTW seems that those classes already not fully functional in a presence of `SecurityManager` that forbids reflective access. The best option here probably is to propose to make original `java.util.*SummaryStatistics` serializable in OpenJDK. Maybe as another acceptable option at expense of addition of fields and probably at a risk of future modifications in originals they can reimplement originals without breaking inheritance. Also seems possible to implement/hack serialization using only public methods of originals for `Int` and `Long` variants, but not sure about `Double` one. Might also be possible to hack them using `Unsafe`, but this will not last long (the same way as in case of `ConcurrentHashMapUnsafe`). And of course there is an options to break inheritance with originals or completely remove them.

And I haven't thought about `org.eclipse.collections.impl.test.Verify` given that being a test utility it has less impact for users.

Hope this helps.

**Comment by nikhilnanivadekar** [comment]
Compilation errors are fixed in #240 , #249

**Comment by nikhilnanivadekar** [comment]
In JDK 9 EA 163 there is a breaking change in java.util.stream.IntPipeline#collect, a new condition `Objects.requireNonNull(combiner)` is added . This breaks `org.eclipse.collections.impl.PersonAndPetKataTest#testStrings` which is fixed in my local. I am putting it here as FYI.

**JDK 9 EA 163:**
![image](https://cloud.githubusercontent.com/assets/9932381/24584109/4bc8a22a-171f-11e7-96b2-572221c2c8ba.png)

**JDK 8:**
![image](https://cloud.githubusercontent.com/assets/9932381/24584116/8810d84c-171f-11e7-82e4-aaa7767b9880.png)

**Comment by nikhilnanivadekar** [comment]
Maven bundle plugin currently does not support Java 9. 
If OSGi, plugin support is not available for Java 9, in a regression build (when we will have one) we will have to add a workaround to to skip this part of build.
See https://issues.apache.org/jira/browse/FELIX-5527 for more info.

**Comment by nikhilnanivadekar** [comment]
Reported 2 bugs to JetBrains
1. [IDEA-170813](https://youtrack.jetbrains.com/issue/IDEA-170813)
2. [IDEA-170814](https://youtrack.jetbrains.com/issue/IDEA-170814)

Reported 1 bug to Eclipse
1. [BUG-514605](https://bugs.eclipse.org/bugs/show_bug.cgi?id=514605)

**Comment by nikhilnanivadekar** [comment]
JetBrains has raised a bug for javac related to [IDEA-170814](https://youtrack.jetbrains.com/issue/IDEA-170814).
Here is the ticket: [JDK-8178150](https://bugs.openjdk.java.net/browse/JDK-8178150)

**Comment by nikhilnanivadekar** [comment]
Step 2 is in #253

**Comment by nikhilnanivadekar** [comment]
Automatic module names in #316

**Comment by nikhilnanivadekar** [comment]
Support added successfully with 9.0.0 release.
