### ISSUE TITLE
ImmutableCollection doesn't extend Collection, etc.

### ISSUE THREAD

**Issue by qblyy** [eclipse/eclipse-collections#290]
ImmutableList, ImmutableSet do not extend List, Set too. It makes that ImmutableCollection etc. can't use together with other libraries.

Guava's design is correct:
public abstract class ImmutableCollection<E> extends AbstractCollection<E> 

public abstract class ImmutableList<E> extends ImmutableCollection<E>
    implements List<E>, RandomAccess

public abstract class ImmutableSet<E> extends ImmutableCollection<E> implements Set<E>

public abstract class ImmutableMap<K, V> implements Map<K, V>, Serializable
...

**Comment by nikhilnanivadekar** [comment]
@qblyy we do not extend the _mutating_ interfaces of JCF by design. It was a conscious decision taken to keep our _Immutable_ interfaces clean. However, each of our implementations implement the JCF interfaces and throw at runtime for mutating methods. To achieve inter-op we have provided API like `castToList()`, `castToSet()`
@motlin has elaborated our Immutable interface design in detail here: https://stackoverflow.com/a/29517706/5182052

**Comment by qblyy** [comment]
Thanks.
