### ISSUE TITLE
Improve OSGi bundle API information

### ISSUE THREAD

**Issue by bergmanngabor** [eclipse/eclipse-collections#319]
We at the Viatra Eclipse project are now experimenting with your amazing collection library, which we consume as an OSGi bundle (via p2 update site).

**What I want to do**: 
Instantiate containers. According to your [reference guide](https://github.com/eclipse/eclipse-collections/blob/master/docs/guide.md#-creating-mutable-collections), collections shall be instantiated either by direct constructor call, or by invoking a static factory method (on _Lists_, _Maps_, etc.). 

**What I experience instead**: 
The OSGi bundle _exports_ neither the actual container implementation classes, nor the static factory classes. Therefore the recommended ways of instantiation is classified as non-API, and Eclipse PDE reports this problem ("discouraged access"). Depending on settings, this may pass as a mere warning at compile time, and be tolerated even at runtime, but not quite ideal.

**What I suggest**: 
I guess you should add _Export-Package_ directives for all these _impl_ packages into your MANIFEST.MF descriptor. Since I believe you encourage advanced users to subclass your collections anyway, this is probably the right choice here, as far as I understand your policy.

Bonus questions: will any older Java 7 compatible versions (or their current maintenance builds) be made available via p2 update sites as well? How about future nightly/milestone pre-release versions?

**Comment by nikhilnanivadekar** [comment]
@bergmanngabor thank you for experimenting with Eclipse Collections!
To be honest, none of us maintainers are OSGi experts, so we have a learning curve ahead of us. If there is something which you need in terms of OSGi bundles, please feel free to contribute. If there is something which we can improve for the bundles, please guide us so we can do the right thing.

This is our p2 build: https://github.com/eclipse/eclipse-collections/blob/master/p2-repository/pom.xml
Seems like we are exporting everything. Is there a setting we are missing?
@guw is there something we might be missing?

For the milestone versions I am working on getting it pushed to maven central as well as p2. However, currently I am encountering issues with jar signing. See Issue #287, #294 . If you have any insights for fixing either of those, please feel free to give your suggestions so that we can get right for 9.0.0 release.
The 9.0.0.M2 (Milestone 2) is scheduled for 8/19, I would like to have these issues sorted out before that.

If you really need older Java 7 and below compatible versions we can discuss that. Currently, we don't have any plans to do a service release for 7.x for p2 repository. The 7.x OSGi bundles were exported via Apache Felix, so may be you can use them but you won't find them in p2 repo.

**Comment by guw** [comment]
FWIW, the *impl* packages are already exported.

As per the rules defined here:
https://github.com/eclipse/eclipse-collections/blob/master/p2-repository/org.eclipse.collections/osgi.bnd

**Comment by nikhilnanivadekar** [comment]
Ah! I see the problem. All the static factories are in impl, and the clients definitely need to call. Is there a way to selectively mark packages non-internal?

**Comment by bergmanngabor** [comment]
> All the static factories are in impl, and the clients definitely need to call. 

Yes, hence the compiler warning, Moreover if `osgi.resolverMode=strict` then an exception will be thrown at runtime as well.

> Is there a way to selectively mark packages non-internal?

You are already selectively marking them as internal, according to the `osgi.bnd` linked above. I wonder if something like the following would do the job?

```
Export-Package: \
 !about.html,!about_files, \
 *.api*;x-internal:=false;version="${package-version}", \
 *.factory*;x-internal:=false;version="${package-version}", \
 *.internal*;x-internal:=true;version="${package-version}", \
 *.impl*;x-internal:=true;version="${package-version}", \
 *;version="${package-version}"
```

Or maybe you could even stop at the line about factory packages, and simply not export the rest - it's up to you I guess. 

In either case, the other recommended strategy for instantiation ("Call the class constructor") would not work still (not that I mind).

**Comment by nikhilnanivadekar** [comment]
From this I think not marking it internal will be the right thing. Would you like to raise a PR? I am planning to release 9.0.0.M2 today, can make it a part of that milestone and you can try it out.

**Comment by guw** [comment]
FWIW, it's compile time warning in Eclipse and Eclipse itself does not use the `osgi.resolverMode=strict`. A lot more stuff would be broken otherwise (there are many bundles using internals).

But if the `impl` packages are public, the `x-internal:=true` flag should be removed. Also note, `x-internal:=false` is redundant and should not be used.

**Comment by nikhilnanivadekar** [comment]
Fixed by #326

**Comment by bergmanngabor** [comment]
Thanks!

Please tell me when you have a CI / milestone build of the OSGi bundle, I would love to try it!
(I won't be back before mid-September, so no pressure.)

**Comment by nikhilnanivadekar** [comment]
@bergmanngabor the next milestone is on Friday the 25th. You can try it on 26th.

**Comment by nikhilnanivadekar** [comment]
@bergmanngabor M3 was released today. Please give it a go! Thanks!

**Comment by bergmanngabor** [comment]
Thanks! I'm going on vacation starting today, so I can give feedback no sooner than early/mid September.

**Comment by bergmanngabor** [comment]
@nikhilnanivadekar I'm back, and I'd love to try the new bundle build. However, I have to admit I have trouble navigating your project web site, and can't find your non-release builds. Can you give me the URL for your milestones/ci update site?

**Comment by nikhilnanivadekar** [comment]
@bergmanngabor you should be able to find it here:
http://download.eclipse.org/collections/9.0.0.M3/repository

**Comment by bergmanngabor** [comment]
I have tried it and it works perfectly. The spurious PDE API warnings are gone. Thanks!
