### ISSUE TITLE
Create a composite repository at http://download.eclipse.org/collections/repository and push zipped artifacts for download

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#387]

**Comment by nikhilnanivadekar** [comment]
@ujhelyiz can you please point me to documentation which will help me with this?
I remember us discussing about creating a composite repository as a part of p2 contribution. May be I am missing the two. Thanks a lot for your help!

**Comment by ujhelyiz** [comment]
I know only a single wiki page of related documentation: https://wiki.eclipse.org/Equinox/p2/Composite_Repositories_(new)

However, the process itself is very simple: you have to select a folder where you put two files named `compositeArtifacts.xml` and `compositeContents.xml` with nearly identical content, where you reference the child repositories (either by absolute or relative urls). If you want to see a live example, look at the composite update site of VIATRA: http://download.eclipse.org/viatra/updates/release/

One more thing that is worth doing because it helps performance: also add a file named `p2.index` with the following contents:

```
version=1
metadata.repository.factory.order=compositeContent.xml,\!
artifact.repository.factory.order=compositeArtifacts.xml,\!
```

I hope this helps; if not, feel free to ask for clarification.

**Comment by nikhilnanivadekar** [comment]
Thank you! I'll try and get back to you.

**Comment by nikhilnanivadekar** [comment]
I think this is fixed and works now.
