### ISSUE TITLE
Implement RichIterable.groupByAndCollect().

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections#47]
Refer to discussion on [pull request 37](https://github.com/eclipse/eclipse-collections/pull/37) for more information. Also, please use the most up-to-date name decided.

**Comment by motlin** [comment]
Full signature:

```java
public static <K, V> Multimap<K, V> groupByCollect(
    Iterable<T> iterable,
    Function<? super T, ? extends K> groupByFunction,
    Function<? super T, ? extends V> collectFunction)
```

**Comment by TheLoneKing** [comment]
I am trying to implement `groupByAndCollect` method on `RichIterable`. My test is failing with errors that looks confusing.
Here are some errors:
1. [ERROR]   `ImmutableSortedBagImplTest.RichIterable_groupByAndCollect` expected: `org.eclipse.collections.impl.map.mutable.UnifiedMap<{false=[12, 10, 8, 6, 4], true=[11, 9, 7, 5, 3]}>` but was: `org.eclipse.collections.impl.map.mutable.UnifiedMap<{false=[12, 10, 8, 6, 4], true=[11, 9, 7, 5, 3]}>`
2. [ERROR]   `ImmutableHashBiMapInverseTest.RichIterable_groupByAndCollect` expected:`<{false=[8, 10, 12, 4, 6], true=[9, 11, 3, 5, 7]}>` but was:`<{false=[4, 6, 8, 10, 12], true=[3, 5, 7, 9, 11]}>`

In case 1, both expected result and the actual result are same. But the test is still failing as if they were different.
In case 2, just the order of the elements in the collection is different. I am not sure why the test is failing because of that.
Here is my implementation and test case: https://github.com/TheLoneKing/eclipse-collections/commit/8f0025f244ee0284efe4a98f8ea6a811e90485c1
Can someone help on how to fix the failing tests?

**Comment by motlin** [comment]
That output doesn’t mean that the expected and actual were the same, just
that their toString() representations are the same. I’m guessing one is a
map of lists and one is a map of sets.
