### ISSUE TITLE
injectInto with primitive result

### ISSUE THREAD

**Issue by victornoel** [eclipse/eclipse-collections#639]
Currently, the signature of injectInto, for example in DoubleIterable, is the following:
```java
<T> T injectInto(T injectedValue, ObjectDoubleToObjectFunction<? super T, ? extends T> function);
```

In the same manner that `collect` has variant for each of the primitives, it could be interesting to have the same with `injectInto`, for example:
```java
double injectIntoDouble(double injectedValue, DoubleBinaryOperator function);
```

This will highly improve performances I believe.

Thanks!

**Comment by nikhilnanivadekar** [comment]
@victornoel feel free to contribute this feature. We can include this in v10.0

**Comment by donraab** [comment]
Hi @victornoel, still interested in contributing this?

**Comment by victornoel** [comment]
Hey hi :) I completely forgot about it ^^ Actually I think I can take a look at it tomorrow, I have a bit of free time :)

**Comment by victornoel** [comment]
In the end I went with simply `injectInto` as the method name.

**Comment by donraab** [comment]
> In the end I went with simply `injectInto` as the method name.

HI @victornoel, I actually prefer the specialized method name `injectIntoDouble` because it avoids potential issues with overloads. There are primitive `injectInto` methods on `RichIterable` that I would like to deprecate and rename matching this pattern because they have caused some ambiguity issues in the past, once lambda support was added to Java 8.

**Comment by victornoel** [comment]
Good point, I've updated the PR :)

**Comment by victornoel** [comment]
Done in #1209.
