### ISSUE TITLE
Optimize removeIf() on BooleanArrayList.

### ISSUE THREAD

**Issue by motlin** [eclipse/eclipse-collections#793]
ArrayList.removeIf() is O(n).
FastList.removeIf() is O(n^2). Same for primitive lists like BooleanArrayList.

**Comment by mohrezaei** [comment]
Huh? FastList.removeIf is not only `O(n)`, but it's a much faster implementation and garbage free.

**Comment by motlin** [comment]
My mistake. Primitive lists are affected, and why I opened the issue. I spot checked FastList to see if it was also affected but somehow missed the override. I'll edit the title.

**Comment by vmzakharov** [comment]
Looking at the removeIf() implementation in FastList and in the mutable primitive lists generated from the template, they look pretty much identical. In fact, it looks like BooleanArrayList is the only one that has an inefficient implementation as it is not code generated (presumably because the underlying data structure is a BitSet rather than an array of booleans).

**Comment by donraab** [comment]
Thanks @vmzakharov! @motlin the code looks identical to me between IntArrayList and FastList. Is there something you are you seeing that we are not?

**Comment by motlin** [comment]
Yes, sorry about that, just BooleanArrayList.
