### ISSUE TITLE
Create a "Working with Eclipse Collections on Github" doc

### ISSUE THREAD

**Issue by cguntur-bnym** [eclipse/eclipse-collections#871]
This doc is either a standalone doc or a section in the CONTRIBUTING.md.

Content is already available and shared with @donraab and @nikhilnanivadekar.

Pending a decision on where to house, after which point, a PR can be submitted.

**Comment by nikhilnanivadekar** [comment]
Put it as a separate doc under the wiki and link it in readme and contribution guide

**Comment by cguntur-bnym** [comment]
@nikhilnanivadekar - I am not sure how to commit a page to the wiki on EC via a fork. Never done that. I'll copy the content on my fork's wiki. You can determine how we move it.

**Comment by nikhilnanivadekar** [comment]
You needn’t commit to a fork, just add a page. Wiki pages are live updated.
There will not be a PR for it :)

**Comment by cguntur-bnym** [comment]
https://github.com/cguntur-bnym/eclipse-collections/wiki/Working-with-Github

**Comment by cguntur-bnym** [comment]
Please review the above, will add to the Wiki directly once you eye-ball.

**Comment by nikhilnanivadekar** [comment]
Only 1 change, add the note that the commit should contain “Closes
#<issueNumber>” when closing an issue.
Content looks great! Thank you!

**Comment by cguntur-bnym** [comment]
Updated: https://github.com/cguntur-bnym/eclipse-collections/wiki/Working-with-Github

**Comment by cguntur-bnym** [comment]
Adding content on EC Wiki

**Comment by nikhilnanivadekar** [comment]
LGTM. We can always update the wiki when needed. :)

**Comment by cguntur-bnym** [comment]
https://github.com/eclipse/eclipse-collections/wiki

https://github.com/eclipse/eclipse-collections/wiki/Working-with-Github

**Comment by cguntur-bnym** [comment]
Will submit a PR for README and CONTRIBUTION updates

**Comment by nikhilnanivadekar** [comment]
Perfect! Thank you very much!

**Comment by jdimeo** [comment]
As I'm working on the Javadocs, I would like to get some eyeballs on it before squashing, as that will make it easier to find and change/reverse hunks as needed than one massive diff. Can squashing happen at the very, very end? what does that workflow look like and should the wiki reflect it?

**Comment by donraab** [comment]
Yes, squashing can happen at the very end.  We'll review the PR and recommend rebasing / squashing right before we merge the PR.  @motlin @nikhilnanivadekar Any comments?

**Comment by jdimeo** [comment]
That's what I thought- thanks @donraab The wiki as it's written seems to say that we should be squashing _before_ we open a PR and for every review/edit "cycle" (as opposed to giving the squash instructions at the very end outside of the "rinse and repeat" loop)

**Comment by motlin** [comment]
@cguntur-bnym I have a number of suggestions for changes.

Step 1 describes forking but not cloning. Include a git clone command. Either explicitly use the word origin or explain that the default remote name is origin. Add the cd command too.

Step 2 for adding the upstream remote is fine, but seems out of place since there's no fetch happening afterwards. I'd either move it later or just go ahead and perform the git fetch --all.

Step 3 "Check out your fork and make the changes" is out of place. Did I do this in step 1 or not? What was I adding the remote to, if not my fork?

Step 4 "Create a proper commit message that starts with the text "Closes #<issue-number>". Link to the [GitHub documentation](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). Any of Closes, Fixes, or Resolves is fine, depending on context. I would never add it at the beginning, always the end. I'd also add the context that you only need to close the issue if it already exists. You don't have to create a new issue just to close it with a PR. A PR *is* an issue (they share a namespace / sequence number)

Step 5 I'm not sure what `git add *` does, but I really doubt it's appropriate. I run commands like `git add -u`, `git add '*.java'`, and `git add -p`. I think what you meant to write is `git add .` or `git add -a` but even those are too powerful to suggest to beginners and only work properly if the `gitignore` files are perfect. It would be better to delete this advice than to recommend adding everything.

Step 6 Since you're writing out a guide, you may as well use the long flag names, rather than explaining the abbreviations. `git commit --signoff --message "My great commit message."`

Step 7 I do run interactive rebases, but I wouldn't recommend it in a guide. If you need this guide, you're too new to git to be running the rebase command at all. Plus this is missing the fetch step, so you'll be rebasing on top of something stale. Instead, recommend running `git pull upstream master --rebase`

Step 8 Delete everything except the force push. Don't specify any branch name at the end, since the branch may not (in fact should not) be named master.

Steps 9 to 12 fine as is

Steps 13 Delete. Don't rebase during a code review unless you have a specific reason to do so (like to resolve known merge conflicts). It makes it harder for the reviewers to track progress over time.

Step 14 It's fine, though it isn't always 1 commit. The point is that edits made in response to review feedback should be squashed into other commit(s) at the last moment.

Step 15 Again says master. People should rarely be working on a branch called master.
