### ISSUE TITLE
Document Deprecation in Contributing.md

### ISSUE THREAD

**Issue by rinatigati** [eclipse/eclipse-collections#977]
@donraab and I ran into a class that needs to be deprecated in #976 but could not find any EC contribution documentation regarding the process.

I believe it's adding the @Deprecated annotation on the class/method in one major version and a TODO to remove the class/method in the next major version. Then obviously removing the class/method in that next major version.

Tagging individuals for a discussion:
@donraab @nikhilnanivadekar @motlin

**Comment by nikhilnanivadekar** [comment]
I don’t think this is necessary. We rarely deprecated anything. If we deprecate anything then I think it’s fairly obvious for folks writing Java code that they need to put an annotation.

**Comment by donraab** [comment]
This is more for explaining the process of how we deprecate and then follow through with removal @nikhilnanivadekar.  We've always said we should deprecate for at least one major version, and then we can decide to remove in the next major version. I think it is worth putting this into text so our understanding as committers is captured for future committers to understand.

**Comment by mohrezaei** [comment]
To be honest, I was never comfortable with that metric for removal. The "standard" in Java is to deprecate but leave things around. This ArrayStack case is an interesting one. Consider the case where one of these classes is serialized to disk. How is anybody supposed to know that and change it? This is especially acute for serializable classes that are not constructable, because it's nearly impossible to do "find usages". 

Having said that, I'm more comfortable with putting a date on the removal instead of version. There is no guarantee that we won't release 12.0 in 3 months. This can be in a comment.

**Comment by donraab** [comment]
Exactly why I thought it is worth discussing. This is the first time we've ever had a container that cannot be created through current APIs but that could still surface through deserialization.
